### ISSUE TITLE
'name'-Input wird im BE von 'disable_mapping'-Feld überlagert

### ISSUE THREAD

**Issue by ericgerhardy** [inspiredminds/contao-content-templates#1]
Erstmal: danke für die Erweiterung, ist genau was ich gesucht habe!

Im Backend werden die beiden Einstellungsfelder nebeneinander angezeigt. Wenn man nun den Titel eines bestehenden Content-Templates bearbeiten will, wird das Input-Feld von dem 'disable_mapping'-Feld überlagert und kann nicht mehr editiert werden.

Eine zusätzliche Klasse "w50" für das 'disable_mapping'-Feld behebt bei mir lokal das Problem.

https://github.com/inspiredminds/contao-content-templates/blob/93784d8fc6fad2ab02acaa414fc372c61a27e453/contao/dca/tl_content_template.php#L88

![Bildschirm­foto 2022-11-30 um 09 39 59](https://user-images.githubusercontent.com/13310987/204748142-9258b29e-8044-4360-8bb9-88328849f53a.png)

**Comment by fritzmg** [comment]
Ist in `1.2.2` nunbehoben :)
